### PR TITLE
Add conditional build macros

### PR DESCRIPTION
**Pull request by FrostbyteGR**
Works the same way by default, but now there are options. Addresses issue #11.

### CODE REVIEW

**Comment by lazyfrosch** [comment]
A few notes:

* Irrelavant for with/without: checker, demo, hello
* pgsql/mysql should also then wrap the parts below for %package, %file and such

Will review this when I have a bit more time

**Comment by dnsmichi** [comment]
Hm, demo and hello are long gone, we should remove their cmake instances.

**Comment by FrostbyteGR** [comment]
Attempted changes based on @lazyfrosch's input.

@dnsmichi Perhaps they should also be removed from the [documentation](https://icinga.com/docs/icinga2/latest/doc/21-development/#cmake-variables) (which I based my requested changes off), as they might cause confusion.

**Comment by dnsmichi** [comment]
Docs are already fixed for 2.11, see https://icinga.com/docs/icinga2/snapshot/doc/21-development/#cmake-variables (I won't go the route with updating 2.10/latest here).

**Comment by dnsmichi** [comment]
CMake variables were already purged, I just did a double check. Seems CMake itself doesn't warn when specifying unknown variables.

**Review by lazyfrosch — APPROVED** [review]
LGTM, thank you for your contribution :green_heart:

**Pull request merged**
